function defaultMemberCover(branchId) {
  const coverMap = {
    douala: '/home/standing-together.jpg',
    bamenda: '/home/celebrating-together.jpg',
    kumbo: '/home/unity-in-support.jpg',
    yaounde: '/home/FB_IMG_1749649752439.jpg',
    bafoussam: '/home/e74dc5c7-8405-4e42-9f20-80aa073608b5.jpg',
    ndop: '/home/1.jpeg',
    nkambe: '/home/standing-together.jpg',
  }

  return coverMap[branchId] || '/home/unity-in-support.jpg'
}

export const demoState = {
  branches: [
    {
      id: 'kumbo',
      name: 'Kumbo Branch',
      location: 'Kumbo',
      description: 'Strong welfare coordination with active youth and family support circles.',
      meetingDay: 'Second Sunday of every month',
      photo:
        'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=900&q=80',
      color: '#165fa6',
      highlights: ['Wedding support', 'Welfare check-ins', 'Youth mentoring'],
      coordinatorName: 'Brenda Nsoh',
      treasurerName: 'Christopher Tabe',
    },
    {
      id: 'bamenda',
      name: 'Bamenda Branch',
      location: 'Bamenda',
      description: 'Known for strong event mobilization, data reporting, and member retention.',
      meetingDay: 'First Saturday of every month',
      photo:
        'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=80',
      color: '#1d7ed8',
      highlights: ['Bereavement solidarity', 'Rapid fundraising', 'Leadership pipeline'],
      coordinatorName: 'Agnes Fon',
      treasurerName: 'Kelly Mbah',
    },
    {
      id: 'douala',
      name: 'Douala Branch',
      location: 'Douala',
      description: 'Commercial hub branch with strong fundraising performance and media engagement.',
      meetingDay: 'Last Sunday of every month',
      photo:
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80',
      color: '#0f4172',
      highlights: ['Media coverage', 'Large membership base', 'Corporate outreach'],
      coordinatorName: 'Linda Atem',
      treasurerName: 'Musa Ebob',
    },
    {
      id: 'yaounde',
      name: 'Yaounde Branch',
      location: 'Yaounde',
      description: 'Administrative branch focusing on policy coordination and national event logistics.',
      meetingDay: 'Third Saturday of every month',
      photo:
        'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=900&q=80',
      color: '#4f94dd',
      highlights: ['National planning', 'Documentation', 'Volunteer coordination'],
      coordinatorName: 'Prisca Ndzi',
      treasurerName: 'Eric Ndzi',
    },
    {
      id: 'bafoussam',
      name: 'Bafoussam Branch',
      location: 'Bafoussam',
      description: 'Community-focused branch with strong charity and outreach partnerships.',
      meetingDay: 'Second Saturday of every month',
      photo:
        'https://images.unsplash.com/photo-1515169067868-5387ec356754?auto=format&fit=crop&w=900&q=80',
      color: '#2b6cb0',
      highlights: ['Charity drives', 'Medical outreach', 'Neighbourhood partnerships'],
      coordinatorName: 'Florence Tchia',
      treasurerName: 'Aurelien Djoum',
    },
    {
      id: 'ndop',
      name: 'Ndop Branch',
      location: 'Ndop',
      description: 'Grassroots branch with strong mutual aid culture and local event attendance.',
      meetingDay: 'Second Friday of every month',
      photo:
        'https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=900&q=80',
      color: '#89b4e2',
      highlights: ['Family support', 'Welfare monitoring', 'Community service'],
      coordinatorName: 'Nelly Che',
      treasurerName: 'Martin Mundi',
    },
    {
      id: 'nkambe',
      name: 'Nkambe Branch',
      location: 'Nkambe',
      description: 'Emerging branch with steady membership growth and excellent turnout.',
      meetingDay: 'Fourth Sunday of every month',
      photo:
        'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=900&q=80',
      color: '#0c4e8c',
      highlights: ['Membership growth', 'Local events', 'Volunteer service'],
      coordinatorName: 'Sarah Taku',
      treasurerName: 'Jude Tanyi',
    },
  ],
  executives: [
    {
      id: 'exec-1',
      name: 'Dr. Mercy Wain',
      portfolio: 'General Coordinator',
      bio: 'Leads the national agenda, branch growth, and strategic partnerships for member welfare.',
      avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Mercy%20Wain&backgroundColor=165fa6',
      phone: '+237 670 000 001',
    },
    {
      id: 'exec-2',
      name: 'Barr. Jude Ngala',
      portfolio: 'Secretary General',
      bio: 'Oversees records, member lists, election archives, and communication standards.',
      avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Jude%20Ngala&backgroundColor=1d7ed8',
      phone: '+237 670 000 002',
    },
    {
      id: 'exec-3',
      name: 'Patricia Mundi',
      portfolio: 'General Treasurer',
      bio: 'Coordinates national contribution reporting, event support records, and financial oversight.',
      avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Patricia%20Mundi&backgroundColor=0f4172',
      phone: '+237 670 000 003',
    },
  ],
  members: [
    { id: 'm1', membershipCode: 'DOUALA-001', name: 'Daniel Taka', username: 'daniel.taka', role: 'super_admin', title: 'Platform Super Admin', branchId: 'douala', phone: '+237 677 101 001', email: 'daniel.taka@circleoffriends.cm', dateOfBirth: '1988-05-10', placeOfBirth: 'Douala', maritalStatus: 'married', homeAddress: 'Bonapriso, Douala', profession: 'IT Administrator', joinedYear: 2016, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Daniel%20Taka&backgroundColor=165fa6', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Douala' },
    { id: 'm2', membershipCode: 'DOUALA-002', name: 'Linda Atem', username: 'linda.atem', role: 'admin', title: 'National Admin', branchId: 'douala', phone: '+237 677 101 002', email: 'linda.atem@circleoffriends.cm', dateOfBirth: '1990-03-14', placeOfBirth: 'Kumbo', maritalStatus: 'married', homeAddress: 'Makepe, Douala', profession: 'Operations Manager', joinedYear: 2017, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Linda%20Atem&backgroundColor=1d7ed8', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Douala' },
    { id: 'm3', membershipCode: 'YAOUNDE-001', name: 'Dr. Mercy Wain', username: 'mercy.wain', role: 'general_coordinator', title: 'General Coordinator', branchId: 'yaounde', phone: '+237 677 101 003', email: 'mercy.wain@circleoffriends.cm', dateOfBirth: '1985-07-02', placeOfBirth: 'Yaounde', maritalStatus: 'married', homeAddress: 'Bastos, Yaounde', profession: 'Medical Doctor', joinedYear: 2014, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Mercy%20Wain&backgroundColor=0f4172', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Yaounde' },
    { id: 'm4', membershipCode: 'YAOUNDE-002', name: 'Barr. Jude Ngala', username: 'jude.ngala', role: 'secretary_general', title: 'Secretary General', branchId: 'yaounde', phone: '+237 677 101 004', email: 'jude.ngala@circleoffriends.cm', dateOfBirth: '1987-09-21', placeOfBirth: 'Bamenda', maritalStatus: 'married', homeAddress: 'Melen, Yaounde', profession: 'Lawyer', joinedYear: 2015, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Jude%20Ngala&backgroundColor=4f94dd', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Yaounde' },
    { id: 'm5', membershipCode: 'BAMENDA-001', name: 'Patricia Mundi', username: 'patricia.mundi', role: 'general_treasurer', title: 'General Treasurer', branchId: 'bamenda', phone: '+237 677 101 005', email: 'patricia.mundi@circleoffriends.cm', dateOfBirth: '1989-11-08', placeOfBirth: 'Bamenda', maritalStatus: 'married', homeAddress: 'Nkwen, Bamenda', profession: 'Accountant', joinedYear: 2015, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Patricia%20Mundi&backgroundColor=2b6cb0', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Bamenda' },
    { id: 'm6', membershipCode: 'KUMBO-001', name: 'Brenda Nsoh', username: 'brenda.nsoh', role: 'branch_coordinator', title: 'Kumbo Branch Coordinator', branchId: 'kumbo', phone: '+237 677 101 006', email: 'brenda.nsoh@circleoffriends.cm', dateOfBirth: '1991-01-17', placeOfBirth: 'Kumbo', maritalStatus: 'single', homeAddress: 'Squares, Kumbo', profession: 'Teacher', joinedYear: 2018, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Brenda%20Nsoh&backgroundColor=165fa6', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Kumbo' },
    { id: 'm7', membershipCode: 'KUMBO-002', name: 'Christopher Tabe', username: 'christopher.tabe', role: 'branch_treasurer', title: 'Kumbo Branch Treasurer', branchId: 'kumbo', phone: '+237 677 101 007', email: 'christopher.tabe@circleoffriends.cm', dateOfBirth: '1990-04-11', placeOfBirth: 'Nkambe', maritalStatus: 'married', homeAddress: 'Kikaikelaki, Kumbo', profession: 'Businessman', joinedYear: 2019, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Christopher%20Tabe&backgroundColor=1d7ed8', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Kumbo' },
    { id: 'm8', membershipCode: 'BAMENDA-002', name: 'Agnes Fon', username: 'agnes.fon', role: 'branch_coordinator', title: 'Bamenda Branch Coordinator', branchId: 'bamenda', phone: '+237 677 101 008', email: 'agnes.fon@circleoffriends.cm', dateOfBirth: '1992-06-03', placeOfBirth: 'Bamenda', maritalStatus: 'married', homeAddress: 'Mile 2, Bamenda', profession: 'Civil Servant', joinedYear: 2018, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Agnes%20Fon&backgroundColor=0f4172', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Bamenda' },
    { id: 'm9', membershipCode: 'BAMENDA-003', name: 'Kelly Mbah', username: 'kelly.mbah', role: 'branch_treasurer', title: 'Bamenda Branch Treasurer', branchId: 'bamenda', phone: '+237 677 101 009', email: 'kelly.mbah@circleoffriends.cm', dateOfBirth: '1993-02-26', placeOfBirth: 'Bafoussam', maritalStatus: 'single', homeAddress: 'Old Town, Bamenda', profession: 'Finance Officer', joinedYear: 2019, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Kelly%20Mbah&backgroundColor=4f94dd', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Bamenda' },
    { id: 'm10', membershipCode: 'DOUALA-003', name: 'Noella Ndzi', username: 'noella.ndzi', role: 'member', title: 'Member', branchId: 'douala', phone: '+237 677 101 010', email: 'noella.ndzi@circleoffriends.cm', dateOfBirth: '1995-12-12', placeOfBirth: 'Yaounde', maritalStatus: 'single', homeAddress: 'Akwa, Douala', profession: 'Marketing Executive', joinedYear: 2020, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Noella%20Ndzi&backgroundColor=2b6cb0', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Douala' },
    { id: 'm11', membershipCode: 'YAOUNDE-003', name: 'Taku Bih', username: 'taku.bih', role: 'member', title: 'Member', branchId: 'yaounde', phone: '+237 677 101 011', email: 'taku.bih@circleoffriends.cm', dateOfBirth: '1996-08-19', placeOfBirth: 'Kumbo', maritalStatus: 'married', homeAddress: 'Emana, Yaounde', profession: 'Engineer', joinedYear: 2021, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Taku%20Bih&backgroundColor=89b4e2', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Yaounde' },
    { id: 'm12', membershipCode: 'NDOP-001', name: 'Nelly Che', username: 'nelly.che', role: 'member', title: 'Member', branchId: 'ndop', phone: '+237 677 101 012', email: 'nelly.che@circleoffriends.cm', dateOfBirth: '1997-10-30', placeOfBirth: 'Ndop', maritalStatus: 'single', homeAddress: 'Central Ndop', profession: 'Nurse', joinedYear: 2022, avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Nelly%20Che&backgroundColor=0c4e8c', status: 'active', approvalStatus: 'approved', approvedBy: 'System bootstrap', approvedAt: '2026-04-08T08:00:00', city: 'Ndop' },
  ].map((member) => ({
    ...member,
    coverPhoto: defaultMemberCover(member.branchId),
  })),
  events: [
    { id: 'event-1', title: 'National Wedding Support for Judith & Emmanuel', type: 'wedding', status: 'upcoming', date: '2026-05-18', venue: 'Douala Grand Hall', summary: 'National contribution drive for a member wedding celebration and hospitality support.', minContribution: 10000, targetAmount: 1250000, raisedAmount: 820000, expenditure: 180000, hero: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1200&q=80', branchScope: 'national' },
    { id: 'event-2', title: 'Member Funeral Support for Late Mr. Nfor', type: 'member-funeral', status: 'ongoing', date: '2026-04-20', venue: 'Bamenda Cultural Centre', summary: 'Condolence support and welfare mobilization for the funeral of a member.', minContribution: 10000, targetAmount: 980000, raisedAmount: 670000, expenditure: 245000, hero: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&q=80', branchScope: 'national' },
    { id: 'event-3', title: 'Immediate Family Funeral Support', type: 'family-funeral', status: 'upcoming', date: '2026-06-07', venue: 'Kumbo Town Hall', summary: 'Solidarity fundraiser to support the bereaved family of a member.', minContribution: 5000, targetAmount: 540000, raisedAmount: 210000, expenditure: 45000, hero: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=1200&q=80', branchScope: 'kumbo' },
    { id: 'event-4', title: 'School Kits Charity Outreach', type: 'charity', status: 'upcoming', date: '2026-07-12', venue: 'Ndop Community School', summary: 'Support for school kits, notebooks, and mentorship sessions for vulnerable children.', minContribution: 5000, targetAmount: 750000, raisedAmount: 320000, expenditure: 95000, hero: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80', branchScope: 'national' },
    { id: 'event-5', title: 'Community Clean-Up and Health Talk', type: 'community', status: 'upcoming', date: '2026-08-02', venue: 'Bafoussam Market Square', summary: 'Community sanitation exercise with preventive health education and referral support.', minContribution: 5000, targetAmount: 420000, raisedAmount: 180000, expenditure: 30000, hero: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80', branchScope: 'bafoussam' },
    { id: 'event-6', title: '2025 National Charity Medical Caravan', type: 'charity', status: 'past', date: '2025-09-15', venue: 'Yaounde District Hospital', summary: 'Free basic consultations, blood pressure screening, and medicine support.', minContribution: 5000, targetAmount: 1100000, raisedAmount: 1340000, expenditure: 520000, hero: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80', branchScope: 'national' },
    { id: 'event-7', title: '2025 Wedding Support for Mr. & Mrs. Ndzi', type: 'wedding', status: 'past', date: '2025-04-18', venue: 'Yaounde Event Centre', summary: 'Wedding contribution drive with decor, hospitality, and member attendance coordination.', minContribution: 10000, targetAmount: 900000, raisedAmount: 1120000, expenditure: 410000, hero: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80', branchScope: 'national' },
  ],
  eventImages: [
    { id: 'ei-1', eventId: 'event-6', imageUrl: '/home/FB_IMG_1749649752439.jpg', sortOrder: 1 },
    { id: 'ei-2', eventId: 'event-6', imageUrl: '/events/convention2020.jpg', sortOrder: 2 },
    { id: 'ei-3', eventId: 'event-6', imageUrl: '/home/e74dc5c7-8405-4e42-9f20-80aa073608b5.jpg', sortOrder: 3 },
    { id: 'ei-4', eventId: 'event-6', imageUrl: '/home/1.jpeg', sortOrder: 4 },
    { id: 'ei-5', eventId: 'event-7', imageUrl: '/home/celebrating-together.jpg', sortOrder: 1 },
    { id: 'ei-6', eventId: 'event-7', imageUrl: '/home/1.jpeg', sortOrder: 2 },
    { id: 'ei-7', eventId: 'event-7', imageUrl: '/home/FB_IMG_1749649752439.jpg', sortOrder: 3 },
    { id: 'ei-8', eventId: 'event-7', imageUrl: '/home/who-we-are-3a.jpg', sortOrder: 4 },
  ],
  contributions: [
    { id: 'c1', eventId: 'event-1', memberId: 'm10', branchId: 'douala', amount: 15000, date: '2026-04-02', kind: 'ongoing' },
    { id: 'c2', eventId: 'event-1', memberId: 'm6', branchId: 'kumbo', amount: 25000, date: '2026-04-03', kind: 'ongoing' },
    { id: 'c3', eventId: 'event-2', memberId: 'm5', branchId: 'bamenda', amount: 30000, date: '2026-04-01', kind: 'ongoing' },
    { id: 'c4', eventId: 'event-2', memberId: 'm7', branchId: 'kumbo', amount: 10000, date: '2026-04-04', kind: 'ongoing' },
    { id: 'c5', eventId: 'event-3', memberId: 'm12', branchId: 'ndop', amount: 5000, date: '2026-03-28', kind: 'ongoing' },
    { id: 'c6', eventId: 'event-4', memberId: 'm3', branchId: 'yaounde', amount: 25000, date: '2026-03-14', kind: 'ongoing' },
    { id: 'c7', eventId: 'event-5', memberId: 'm2', branchId: 'douala', amount: 20000, date: '2026-03-20', kind: 'ongoing' },
    { id: 'c8', eventId: 'event-6', memberId: 'm4', branchId: 'yaounde', amount: 20000, date: '2025-09-10', kind: 'late' },
    { id: 'c9', eventId: 'event-6', memberId: 'm10', branchId: 'douala', amount: 10000, date: '2025-09-12', kind: 'ongoing' },
    { id: 'c10', eventId: 'event-7', memberId: 'm11', branchId: 'yaounde', amount: 20000, date: '2025-04-05', kind: 'ongoing' },
  ],
  posts: [
    {
      id: 'p1',
      authorId: 'm10',
      branchId: 'douala',
      type: 'photo',
      content: 'Douala branch media team has uploaded fresh wedding decor samples for the May support event.',
      createdAt: '2026-04-07T08:15:00',
      media: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80',
      attachments: ['Event-plan.pdf', 'Decor-budget.xlsx'],
      reactions: 42,
      comments: 12,
    },
    {
      id: 'p2',
      authorId: 'm6',
      branchId: 'kumbo',
      type: 'video',
      content: 'Kumbo welfare committee has shared a short clip from the condolence visit earlier today.',
      createdAt: '2026-04-06T14:40:00',
      media: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80',
      attachments: ['Visit-report.docx'],
      reactions: 37,
      comments: 9,
    },
    {
      id: 'p3',
      authorId: 'm4',
      branchId: 'yaounde',
      type: 'file',
      content: 'Secretary General has published the updated branch attendance register and election preparation guide.',
      createdAt: '2026-04-05T11:10:00',
      media: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
      attachments: ['Attendance-register.xlsx', 'Election-guide.pdf'],
      reactions: 28,
      comments: 6,
    },
  ],
  announcements: [
    {
      id: 'a1',
      title: 'Monthly General Assembly',
      message: 'All branches should finalize attendance sheets and welfare updates before Friday 6PM.',
      audience: 'All members',
      createdAt: '2026-04-06T08:00:00',
      authorId: 'm4',
      channel: 'website+whatsapp',
    },
    {
      id: 'a2',
      title: 'Wedding Support Dress Code',
      message: 'The national wedding support event dress code is royal blue, white, and soft silver.',
      audience: 'National event volunteers',
      createdAt: '2026-04-05T15:15:00',
      authorId: 'm3',
      channel: 'website',
    },
  ],
}
